/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LiveRouteImport } from './routes/live'
import { Route as MapsRouteImport } from './routes/maps'
import { Route as ApiPublicRsuTelemetryRouteImport } from './routes/api/public/rsu/telemetry'
import { Route as ApiPublicVehicleTelemetryRouteImport } from './routes/api/public/vehicle/telemetry'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveRoute = LiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => rootRouteImport,
} as any)
const MapsRoute = MapsRouteImport.update({
  id: '/maps',
  path: '/maps',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicRsuTelemetryRoute = ApiPublicRsuTelemetryRouteImport.update({
  id: '/api/public/rsu/telemetry',
  path: '/api/public/rsu/telemetry',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicVehicleTelemetryRoute =
  ApiPublicVehicleTelemetryRouteImport.update({
    id: '/api/public/vehicle/telemetry',
    path: '/api/public/vehicle/telemetry',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/live': typeof LiveRoute
  '/maps': typeof MapsRoute
  '/api/public/rsu/telemetry': typeof ApiPublicRsuTelemetryRoute
  '/api/public/vehicle/telemetry': typeof ApiPublicVehicleTelemetryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/live': typeof LiveRoute
  '/maps': typeof MapsRoute
  '/api/public/rsu/telemetry': typeof ApiPublicRsuTelemetryRoute
  '/api/public/vehicle/telemetry': typeof ApiPublicVehicleTelemetryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/live': typeof LiveRoute
  '/maps': typeof MapsRoute
  '/api/public/rsu/telemetry': typeof ApiPublicRsuTelemetryRoute
  '/api/public/vehicle/telemetry': typeof ApiPublicVehicleTelemetryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/live'
    | '/maps'
    | '/api/public/rsu/telemetry'
    | '/api/public/vehicle/telemetry'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/live'
    | '/maps'
    | '/api/public/rsu/telemetry'
    | '/api/public/vehicle/telemetry'
  id:
    | '__root__'
    | '/'
    | '/live'
    | '/maps'
    | '/api/public/rsu/telemetry'
    | '/api/public/vehicle/telemetry'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LiveRoute: typeof LiveRoute
  MapsRoute: typeof MapsRoute
  ApiPublicRsuTelemetryRoute: typeof ApiPublicRsuTelemetryRoute
  ApiPublicVehicleTelemetryRoute: typeof ApiPublicVehicleTelemetryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live': {
      id: '/live'
      path: '/live'
      fullPath: '/live'
      preLoaderRoute: typeof LiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maps': {
      id: '/maps'
      path: '/maps'
      fullPath: '/maps'
      preLoaderRoute: typeof MapsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/rsu/telemetry': {
      id: '/api/public/rsu/telemetry'
      path: '/api/public/rsu/telemetry'
      fullPath: '/api/public/rsu/telemetry'
      preLoaderRoute: typeof ApiPublicRsuTelemetryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/vehicle/telemetry': {
      id: '/api/public/vehicle/telemetry'
      path: '/api/public/vehicle/telemetry'
      fullPath: '/api/public/vehicle/telemetry'
      preLoaderRoute: typeof ApiPublicVehicleTelemetryRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LiveRoute: LiveRoute,
  MapsRoute: MapsRoute,
  ApiPublicRsuTelemetryRoute: ApiPublicRsuTelemetryRoute,
  ApiPublicVehicleTelemetryRoute: ApiPublicVehicleTelemetryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
